version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.4.0"
    working_directory: /Users/distiller/project
    environment:
      # FL_OUTPUT_DIR: output
      # FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Build
          command: xcodebuild -scheme xcode-poc  -sdk iphonesimulator -derivedDataPath Build/ -destination name="iPhone 8" -enableCodeCoverage YES clean test
      - run:
          name: Convert coverage report
          command: |
            XCRESULT=`find ./Build/Logs/Test -name "*.xcresult"`
            echo Converting $XCRESULT to Codecov .json format
            ./bin/generate-codecov-json-macos ----archive-path XCRESULT
            cat coverage-report-*
      # - run:
      #     name: Upload coverage to Codecov
      #     command:
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  # adhoc:
  #   macos:
  #     xcode: "10.2.0"
  #   working_directory: /Users/distiller/project
  #   environment:
  #     FL_OUTPUT_DIR: output
  #     FASTLANE_LANE: adhoc
  #   shell: /bin/bash --login -o pipefail
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     - run:
  #         name: Fastlane
  #         command: bundle exec fastlane $FASTLANE_LANE
  #     - store_artifacts:
  #         path: output/Game.ipa

  # beta:
  #   macos:
  #     xcode: "10.2.0"
  #   working_directory: /Users/distiller/project
  #   environment:
  #     FL_OUTPUT_DIR: output
  #     FASTLANE_LANE: beta
  #   shell: /bin/bash --login -o pipefail
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     - run:
  #         name: Fastlane
  #         command: bundle exec fastlane $FASTLANE_LANE
  #     - store_artifacts:
  #         path: output/Game.ipa

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
      # - adhoc:
      #     filters:
      #       branches:
      #         only: development
      #     requires:
      #       - build-and-test
      #- beta:
          #filters:
            #branches:
              #only: master
          #requires:
            #- build-and-test
